version: "3.7"

services:
  postfix:
    image: mwader/postfix-relay
    container_name: postfix
    environment:
      - POSTFIX_myhostname=smtp.localdomain
      - POSTFIX_mynetworks=0.0.0.0/0
      - OPENDKIM_DOMAINS=
    ports:
      - "1025:25"
    restart: unless-stopped
