// Static fallback for playlists when browser cannot reach YouTube's full API (RSS caps at 15).
// Regenerate after major playlist changes: fetch playlist HTML and update this file.
window.PLAYLIST_STATIC_ITEMS = {
  PL8qeqP57-QAZz8wi1x7toEWzPC_mW5NfO: [
    { videoId: 'iWmDSH21cTY', title: 'Why Learn Python ? Mastering Data Science: Python Unveiled! 🚀 Explore, Learn, Excel!' },
    { videoId: 'ztEnaCr8X6A', title: '#01 || Google Colab Tutorial | Step-by-Step Guide for Beginners' },
    { videoId: 'fvC2jcGyTWs', title: '#02 || Keywords & Identifiers & Comments || Python For Data Science' },
    { videoId: 'lWzrUJN_iGQ', title: '#03 | Indentation & Statements & Variables || Python For Data Science' },
    { videoId: 'M9MdMtlWjVQ', title: '#04 || Data Types vs. Data Structures Explained || Python for Data Science' },
    { videoId: '02RL7UYbo-0', title: '#05 || Numeric Data types & Strings  || Python For Data Science' },
    { videoId: 'RPWSQ1W7Xss', title: '#06 || Lists in Python || Methods and Manipulation || Python For Data Science' },
    { videoId: 'FzEHpiuGuV8', title: '#07 || Tuples in Python || Mastering Immutable data structures || Python For Data Science' },
    { videoId: 'iwHWYQLraWs', title: '#08 || Sets in Python || Methods and Manipulations || Python for Data Science' },
    { videoId: 'm5OL19oMgWE', title: '#09 || Dictionaries in Python || Methods and Manipulations || Python for Data Science' },
    { videoId: 'Isv-Cntut6E', title: '#10 || Type Casting In Python || Very Easy || Python for Data Science' },
    { videoId: 'MkDn1ygA2V0', title: '#11 || Operators in Python || Part 1 || Python for Data Science' },
    { videoId: '16IMUjkgqm8', title: '#12 || Bitwise Operators in Python || 2\'s Complement ... || Python For Data Science' },
    { videoId: 'MlAycaXUNTA', title: '#13 || If else statement tutorial Python || Python for Data Science' },
    { videoId: '_2vImJ_YJfo', title: '#14 || While Loops in Python || How to avoid infinite loops || Python for Data Science' },
    { videoId: 'eDvLR4DuoI4', title: '#15 || Python For Loop Tutorial || Real life examples || Python for data science' },
    { videoId: 'ma3SlNjF-NM', title: '#16 || Break 🆚 Continue 🆚 Pass Statement in Python || Python for Data Science' },
    { videoId: 'qEZ7nPLjt40', title: '#17 || Functions in Python || Python for Data Science' },
    { videoId: 'n0QbyAYLBcM', title: '#18 || Arguments vs Parameters in Functions || args vs kwargs || Python for Data Science' },
    { videoId: 'nd1Wh_FESeM', title: '#19 || Map reduce filter in python || Inbuilt vs User Defined Functions in Python' },
    { videoId: 'zm07PrSK6is', title: '#20 || Recursive Functions and Lambda Functions in Python || Python for Data Science' },
    { videoId: 'o4EjbjquAt0', title: '#21 || Exception Handling in Python || Try Except Finally explained in detail!' },
    { videoId: 'L5NdPKTUlWY', title: '#22 || File Handling in Python - Reading and writing to files || Python for Data Science' },
    { videoId: 'LwfGWgbBgr4', title: '#23 || Complete Numpy from Scratch - Part 1 || Python for Data Science' },
    { videoId: 'heAWC5UQTZw', title: '#24 || Complete Numpy from Scratch - Part 2 || Python for Data Science' },
    { videoId: 'LdDBAaAIh90', title: '#25 || Complete Numpy from Scratch - Part 3 || Python for Data Science' },
    { videoId: '91C04FZUgKs', title: '#26 || Complete Pandas from Scratch - Part 1 || Python for DataScience #Pandas' },
    { videoId: 'JAgXPCK-a8k', title: '#27 || Complete Pandas from Scratch - Part 2 || Delete Records, Slicing & Indexing in DataFrames' },
    { videoId: '_zNo-CWzqew', title: '#28 || Pandas from Scratch Part3 || Loc vs iLoc in DataFrames with detailed Examples' },
    { videoId: 'LKb63TcJs9g', title: '#29 || Pandas from Scratch - Part 4 || Sort Rows, Sort Columns & Rearrange Columns in DataFrames' },
    { videoId: 'nLqkyKZZXUs', title: '#30 || How to deal with Null Values in DataFrames ?|| Pandas from Scratch - Part 5' },
    { videoId: 'ziJrKWsJB0g', title: '#31 || Filtering and GroupBy in DataFrames || Pandas from Scratch - Part 6' },
    { videoId: '1r-yodra1pg', title: '#32 || Join VS Merge VS Concat in DataFrames || Pandas from Scratch - Part 7' },
  ],
};
